"""record chunk content type

Revision ID: 1c6e5a4fe267
Revises: 89e49a9bc695
Create Date: 2026-08-24 17:20:42.651440
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1c6e5a4fe267"
down_revision: str | None = "89e49a9bc695"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Record whether a chunk's text was read or recognised.

    Autogenerate proposed this as NOT NULL with no default, which would fail
    outright on a table that already has rows — there is no value to give
    them. Adding a server default fixes that, and in Postgres 11+ a NOT NULL
    column WITH a default is a catalogue-only change: no table rewrite, no
    long lock, regardless of how many chunks exist.

    The default is kept rather than dropped afterwards, so a chunk written by
    anything that does not know about this column still lands as "text",
    which is the truthful value for every existing row.
    """
    op.add_column(
        "chunks",
        sa.Column("content_type", sa.String(length=16), nullable=False, server_default="text"),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chunks", "content_type")
    # ### end Alembic commands ###
