"""persist citations on messages

Revision ID: 89e49a9bc695
Revises: 92d321f6109f
Create Date: 2026-08-24 14:42:34.660873
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "89e49a9bc695"
down_revision: str | None = "92d321f6109f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add a nullable snapshot of the sources behind each assistant turn.

    Nullable on purpose, and safe on a live table: adding a nullable column
    with no default is a catalogue-only change in Postgres, so it does not
    rewrite the table or take a long lock.

    Existing assistant messages keep NULL. They were written before sources
    were recorded and there is nothing to backfill from — the chunks that
    grounded them may since have been deleted. The API reports NULL as an
    empty list, so old conversations render exactly as they did before.
    """
    op.add_column(
        "messages", sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "citations")
    # ### end Alembic commands ###
